### ISSUE TITLE
Typo Issue

### ISSUE THREAD

**Issue by NikSWE** [sb2nov/sb2nov.github.io#30]
<img width="899" alt="Screenshot 2021-09-12 at 7 49 34 PM" src ="https://user-images.githubusercontent.com/34477129/132991209-78cf4bbc-85e8-4a32-b814-ef7060d499a8.png">

Hey @sb2nov, just found a typo in your projects sections. didn't have docker on machine at the moment so just created this issue 😃

**Comment by sb2nov** [comment]
thanks just sent out the fix﻿
